import { Dimensions, StyleSheet } from "react-native";

const { width, height } = Dimensions.get("window");

export const surveyStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F5F7FA",
  },
  backgroundImage: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: -300,
    width: width,
    height: height,
    resizeMode: "cover",
  },
  content: {
    flex: 1,
    justifyContent: "flex-start",
    alignItems: "center",
    paddingHorizontal: 15,
    paddingVertical: 10,
  },
  card: {
    backgroundColor: "white",
    borderRadius: 32,
    paddingTop: 30,
    paddingBottom: 30,
    paddingLeft: 60,
    paddingRight: 60,
    width: "100%",
    maxWidth: 1100,
    minHeight: height * 0.45,
    borderWidth: 2,
    borderColor: "#e0e0e0",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 8,
  },
  header: {
    alignItems: "center",
    marginBottom: 18,
  },
  titleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    marginBottom: 8,
  },
  title: {
    fontSize: 44,
    color: "#1A1A1A",
    fontWeight: "700",
    textAlign: "center",
  },
  titleNepali: {
    fontSize: 36,
    color: "#1A1A1A",
    fontWeight: "500",
    textAlign: "center",
  },
  subtitle: {
    fontSize: 20,
    color: "#666",
    marginBottom: 4,
    textAlign: "center",
  },
  optionsContainer: {
    marginBottom: 20,
    width: "100%",
  },
  optionRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 18,
    paddingVertical: 24,
    paddingHorizontal: 35,
    backgroundColor: "#f8f9fa",
    borderRadius: 24,
    borderWidth: 3,
    borderColor: "#e8e8e8",
    minHeight: 90,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 3,
  },
  circleContainer: {
    marginRight: 25,
    marginTop: 0,
    justifyContent: "center",
    alignItems: "center",
  },
  coloredCircle: {
    width: 45,
    height: 45,
    borderRadius: 22.5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  radioContainer: {
    marginRight: 25,
    marginTop: 0,
    justifyContent: "center",
    alignItems: "center",
  },
  radioOuter: {
    width: 45,
    height: 45,
    borderRadius: 22.5,
    borderWidth: 4,
    justifyContent: "center",
    alignItems: "center",
  },
  radioInner: {
    width: 22,
    height: 22,
    borderRadius: 11,
  },
  optionContent: {
    flex: 1,
  },
  optionLabel: {
    fontSize: 28,
    fontFamily: "Outfit_400Regular",
    color: "#1A1A1A",
    marginBottom: 0,
    lineHeight: 36,
  },
  hindiText: {
    fontFamily: "Outfit_400Regular",
  },
  thankYouCardContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
  },
  thankYouInner: {
    alignItems: "center",
    paddingVertical: 40,
  },
  smileyTextRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 40,
  },
  smileyImage: {
    width: 64,
    height: 64,
    marginRight: 20,
  },
  thankYouTitleContainer: {
    alignItems: "center",
  },
  thankYouTitle: {
    fontSize: 42,
    fontFamily: "Outfit_700Bold",
    color: "#1A1A1A",
    textAlign: "center",
    marginBottom: 5,
  },
  thankYouTitleNepali: {
    fontSize: 34,
    fontFamily: "Outfit_600SemiBold",
    color: "#1A1A1A",
    textAlign: "center",
  },
  thankYouSubtitle: {
    fontSize: 24,
    fontFamily: "Outfit_600SemiBold",
    color: "#4CAF50",
    marginBottom: 8,
    textAlign: "center",
  },
  thankYouSubtitleNepali: {
    fontSize: 20,
    fontFamily: "Outfit_500Medium",
    color: "#4CAF50",
    marginBottom: 25,
    textAlign: "center",
  },
  thankYouDescription: {
    fontSize: 20,
    fontFamily: "Outfit_400Regular",
    color: "#666666",
    textAlign: "center",
    lineHeight: 30,
    paddingHorizontal: 25,
    marginBottom: 8,
  },
  thankYouDescriptionNepali: {
    fontSize: 18,
    fontFamily: "Outfit_400Regular",
    color: "#666666",
    textAlign: "center",
    lineHeight: 28,
    paddingHorizontal: 25,
  },
  governmentInfoContainer: {
    alignItems: "center",
    marginBottom: 20,
    marginTop: 5,
    paddingHorizontal: 30,
    width: "100%",
  },
  governmentMainText: {
    fontSize: 18,
    fontFamily: "Outfit_700Bold",
    color: "#C00",
    marginBottom: 3,
  },
  governmentDeptText: {
    fontSize: 16,
    fontFamily: "Outfit_600SemiBold",
    color: "#C00",
    marginBottom: 2,
    textAlign: "center",
  },
  governmentCellText: {
    fontSize: 16,
    fontFamily: "Outfit_400Regular",
    color: "#C00",
    marginBottom: 2,
    textAlign: "center",
  },
  governmentLocationText: {
    fontSize: 14,
    fontFamily: "Outfit_400Regular",
    color: "#C00",
    textAlign: "center",
  },
  logoTopLeft: {
    position: "absolute",
    top: 15,
    left: 25,
    width: 95,
    height: 95,
  },
  logoTopRight: {
    position: "absolute",
    top: 15,
    right: 25,
    width: 95,
    height: 95,
  },
  nepaliSubtitleButton: {
    padding: 12,
    borderRadius: 8,
  },
  nepaliSubtitleText: {
    fontSize: 18,
    color: "#666",
    marginBottom: 15,
    textAlign: "center",
  },
});
