import { Dimensions, StyleSheet } from "react-native";

const { width, height } = Dimensions.get("window");

export const surveyStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F5F7FA",
  },
  backgroundImage: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: -300,
    width: width,
    height: height,
    resizeMode: "cover",
  },
  content: {
    flex: 1,
    justifyContent: "flex-start",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 15,
  },
  card: {
    backgroundColor: "white",
    borderRadius: 28,
    paddingTop: 30,
    paddingBottom: 30,
    paddingLeft: 50,
    paddingRight: 50,
    width: "98%",
    maxWidth: 700,
    borderWidth: 1,
    borderColor: "#efefef",
  },
  header: {
    alignItems: "center",
    marginBottom: 10,
  },
  title: {
    fontSize: 38,
    color: "#1A1A1A",
    marginBottom: 2,
    textAlign: "center",
  },
  customBold: {
    fontWeight: "500",
    letterSpacing: 0.2,
  },
  titleNepali: {
    fontSize: 24,
    color: "#1A1A1A",
    marginBottom: 6,
    textAlign: "center",
  },
  subtitle: {
    fontSize: 15,
    color: "#888",
    marginBottom: 2,
    textAlign: "center",
  },
  optionsContainer: {
    marginBottom: 30,
  },
  optionRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 24,
    paddingVertical: 20,
    paddingHorizontal: 24,
    backgroundColor: "transparent",
    borderRadius: 18,
    borderWidth: 4,
    borderColor: "#efefef",
  },
  radioContainer: {
    marginRight: 14,
    marginTop: 0,
    justifyContent: "center",
    alignItems: "center",
  },
  radioOuter: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 3,
    justifyContent: "center",
    alignItems: "center",
  },
  radioInner: {
    width: 16,
    height: 16,
    borderRadius: 8,
  },
  optionContent: {
    flex: 1,
  },
  optionLabel: {
    fontSize: 22,
    fontFamily: "Outfit_400Regular",
    color: "#1A1A1A",
    marginBottom: 4,
  },
  hindiText: {
    fontFamily: "Outfit_400Regular",
  },
  thankYouCardContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
  },
  thankYouInner: {
    alignItems: "center",
    paddingVertical: 20,
  },
  smileyTextRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 30,
  },
  smileyImage: {
    width: 48,
    height: 48,
    marginRight: 12,
  },
  thankYouTitle: {
    fontSize: 32,
    fontFamily: "Outfit_700Bold",
    color: "#1A1A1A",
    textAlign: "center",
  },
  thankYouSubtitle: {
    fontSize: 18,
    fontFamily: "Outfit_600SemiBold",
    color: "#4CAF50",
    marginBottom: 20,
    textAlign: "center",
  },
  thankYouDescription: {
    fontSize: 16,
    fontFamily: "Outfit_400Regular",
    color: "#666666",
    textAlign: "center",
    lineHeight: 24,
    paddingHorizontal: 20,
  },
  governmentInfoContainer: {
    alignItems: "center",
    marginBottom: 20,
    marginTop: 10,
    paddingHorizontal: 30,
    width: "100%",
  },
  governmentMainText: {
    fontSize: 15,
    fontFamily: "Outfit_700Bold",
    color: "#C00",
    marginBottom: 2,
  },
  governmentDeptText: {
    fontSize: 13,
    fontFamily: "Outfit_600SemiBold",
    color: "#C00",
    marginBottom: 1,
    textAlign: "center",
  },
  governmentCellText: {
    fontSize: 13,
    fontFamily: "Outfit_400Regular",
    color: "#C00",
    marginBottom: 1,
    textAlign: "center",
  },
  governmentLocationText: {
    fontSize: 12,
    fontFamily: "Outfit_400Regular",
    color: "#C00",
    textAlign: "center",
  },
  logoTopLeft: {
    position: "absolute",
    top: 14,
    left: 36,
    width: 80,
    height: 80,
  },
  logoTopRight: {
    position: "absolute",
    top: 14,
    right: 36,
    width: 80,
    height: 80,
  },
  nepaliSubtitleButton: {
    padding: 10,
    borderRadius: 5,
  },
  nepaliSubtitleText: {
    fontSize: 14,
    color: "#888",
    marginBottom: 10,
    textAlign: "center",
  },
});
