import { Dimensions, StyleSheet } from "react-native";

const { width, height } = Dimensions.get("window");

export const surveyStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F5F7FA",
  },
  backgroundImage: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: -300,
    width: width,
    height: height,
    resizeMode: "cover",
  },
  content: {
    flex: 1,
    justifyContent: "flex-start",
    alignItems: "center",
    paddingHorizontal: 15,
    paddingVertical: 10,
  },
  card: {
    backgroundColor: "white",
    borderRadius: 16,
    paddingTop: 12,
    paddingBottom: 12,
    paddingLeft: 25,
    paddingRight: 25,
    width: "100%",
    maxWidth: 900,
    minHeight: undefined,
    borderWidth: 2,
    borderColor: "#e0e0e0",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 8,
  },
  header: {
    alignItems: "center",
    marginBottom: 6,
  },
  titleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    marginBottom: 4,
  },
  title: {
    fontSize: 24,
    color: "#1A1A1A",
    fontWeight: "700",
    textAlign: "center",
  },
  titleNepali: {
    fontSize: 20,
    color: "#1A1A1A",
    fontWeight: "500",
    textAlign: "center",
  },
  subtitle: {
    fontSize: 14,
    color: "#666",
    marginBottom: 4,
    textAlign: "center",
  },
  optionsContainer: {
    marginBottom: 5,
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "stretch",
    gap: 0,
  },
  optionRow: {
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "flex-start",
    paddingVertical: 28,
    paddingHorizontal: 16,
    backgroundColor: "#f8f9fa",
    borderRadius: 18,
    borderWidth: 2,
    borderColor: "#e8e8e8",
    minHeight: 220,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
    flex: 1,
    marginHorizontal: 4,
    maxWidth: "90%",
  },
  circleContainer: {
    justifyContent: "center",
    alignItems: "center",
    marginTop: 0,
  },
  coloredCircle: {
    width: 70,
    height: 70,
    borderRadius: 50,
    marginBottom: 0,
    marginTop: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.13,
    shadowRadius: 4,
    elevation: 3,
  },
  radioContainer: {
    marginRight: 15,
    marginTop: 0,
    justifyContent: "center",
    alignItems: "center",
  },
  radioOuter: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 4,
    justifyContent: "center",
    alignItems: "center",
  },
  radioInner: {
    width: 14,
    height: 14,
    borderRadius: 7,
  },
  optionContent: {
    flex: 1,
  },
  optionLabel: {
    fontSize: 28,
    fontFamily: "Outfit_400Regular",
    color: "#1A1A1A",
    marginTop: 18,
    textAlign: "center",
    marginBottom: 0,
  },
  hindiText: {
    fontFamily: "Outfit_400Regular",
    fontSize: 28,
    textAlign: "center",
    marginTop: 2,
  },
  thankYouCardContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
  },
  thankYouInner: {
    alignItems: "center",
    paddingVertical: 25,
  },
  smileyTextRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 25,
  },
  smileyImage: {
    width: 48,
    height: 48,
    marginRight: 15,
  },
  thankYouTitleContainer: {
    alignItems: "center",
  },
  thankYouTitle: {
    fontSize: 32,
    fontFamily: "Outfit_700Bold",
    color: "#1A1A1A",
    textAlign: "center",
    marginBottom: 4,
  },
  thankYouTitleNepali: {
    fontSize: 26,
    fontFamily: "Outfit_600SemiBold",
    color: "#1A1A1A",
    textAlign: "center",
  },
  thankYouSubtitle: {
    fontSize: 18,
    fontFamily: "Outfit_600SemiBold",
    color: "#4CAF50",
    marginBottom: 6,
    textAlign: "center",
  },
  thankYouSubtitleNepali: {
    fontSize: 16,
    fontFamily: "Outfit_500Medium",
    color: "#4CAF50",
    marginBottom: 15,
    textAlign: "center",
  },
  thankYouDescription: {
    fontSize: 16,
    fontFamily: "Outfit_400Regular",
    color: "#666666",
    textAlign: "center",
    lineHeight: 22,
    paddingHorizontal: 15,
    marginBottom: 6,
  },
  thankYouDescriptionNepali: {
    fontSize: 14,
    fontFamily: "Outfit_400Regular",
    color: "#666666",
    textAlign: "center",
    lineHeight: 20,
    paddingHorizontal: 15,
  },
  governmentInfoContainer: {
    alignItems: "center",
    marginBottom: 20,
    marginTop: 5,
    paddingHorizontal: 30,
    width: "100%",
  },
  governmentMainText: {
    fontSize: 18,
    fontFamily: "Outfit_700Bold",
    color: "#C00",
    marginBottom: 3,
  },
  governmentDeptText: {
    fontSize: 16,
    fontFamily: "Outfit_600SemiBold",
    color: "#C00",
    marginBottom: 2,
    textAlign: "center",
  },
  governmentCellText: {
    fontSize: 16,
    fontFamily: "Outfit_400Regular",
    color: "#C00",
    marginBottom: 2,
    textAlign: "center",
  },
  governmentLocationText: {
    fontSize: 14,
    fontFamily: "Outfit_400Regular",
    color: "#C00",
    textAlign: "center",
  },
  logoTopLeft: {
    position: "absolute",
    top: 15,
    left: 25,
    width: 95,
    height: 95,
  },
  logoTopRight: {
    position: "absolute",
    top: 15,
    right: 25,
    width: 95,
    height: 95,
  },
  nepaliSubtitleButton: {
    paddingLeft: 12,
    paddingRight: 12,
    paddingBottom: 12,
    borderRadius: 8,
  },
  nepaliSubtitleText: {
    fontSize: 12,
    color: "#666",
    textAlign: "center",
  },
  loadingContainer: {
    alignItems: "center",
    marginTop: 15,
    paddingVertical: 10,
  },
  loadingText: {
    fontSize: 16,
    fontFamily: "Outfit_500Medium",
    color: "#666",
    textAlign: "center",
  },
});
